title: Deleterr
description: Automated media library management for Plex with Radarr/Sonarr integration
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  toc_levels: 2..3
  auto_ids: true
